
base:
    seed: 42


data:
    path_data: 'datasets\labeled\data_w30_labeled.pickle'
    path_data_augmented: 'datasets\labeled\data_w30_labeled_augmented.pickle'
    data_setting:
        add_artificial: True
        artificial_samples: 20
        max_artificial_peak_height: 15


reconstructor: 
    # select type betweeen autoencoder or pca
    type: autoencoder
    autoencoder:
        latent_dim: 24
        model_path: models/autoencoders
    pca:
        latent_dim: 512
        model_path: models/pca


detector:
    type: OS_CFAR
    os_cfar:
        N: 190
        T: 6.9
        N_protect: 10


neural_net:
    hidden_neurons: 100
    dropout:        0.0
    batch_size:     16
    learning_rate:  0.01
    epochs:         100
    self_normalize: False


results:
    model_path: 'models\classifiers'
    plot_settings:  
        plot_path: 'reports\plots'
        plot_format: 'png'


    