
data:
    path_data: datasets\labeled\data_w30_labeled.pickle
    path_data_augmented: datasets\ata_w30_labeled_augmented.pickle
    save_dir: datasets\labeled


pipeline_i:


pipeline_ii:


pipeline_iii:


pipeline_iv:
    autoencoder:
        latent_dim: 24
        model_path: models/autoencoders/autoencoder24.pth

    neural_net: 
        hyperparams:
            hidden_neurons: 100
            dropout:        0.0
            batch_size:     32
            learning_rate:  0.01
            epochs:         1000


results:
    plot_path: 'reports\plots'


    